---
driver:
  name: ec2
  aws_ssh_key_id: chef-learning
  region: us-west-2
  availability_zone: a
  subnet_id: subnet-3495f85f
  instance_type: t2.micro
  image_id: ami-0def3275
  security_group_ids: ["sg-50a1652c"]
  retryable_tries: 120

provisioner:
  name: chef_zero

verifier:
  name: inspec

transport:
  ssh_key: /home/vagrant/chef-learning.pem

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[squid::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
